### ISSUE TITLE
Playdate port?

### ISSUE THREAD

**Issue by wallmasterr** [michel-iwaniec/bb-studio#6]
Hi this is great I was just wondering if you would be interested making a playdate port of this? The playdate engines/tools are mainly codebases and a gbstudio-like for it would be great for the community.
There is a dedicated fanbase willing to buy most things. 
The nes is the same vertical resolution as the playdate so that would work fine. 
They can both compile with c
How much effort was this port and how much do you think a playdate one would be?

I would be willing to contribute some money towards such a project port

Thanks 
Ally from Lowtek Games (creator of Flea, tapweorm disco puzzle and chewchew mimic )

**Comment by michel-iwaniec** [comment]
Sorry, but I have no intention of doing a Playdate port. I already have my plate full with this one - and other future ideas :)

A Playdate port would be kind of cool though. If somebody wishes to pursue it, then best of luck with that mission!
